package com.rmsr.myguard.domain.utils


import com.google.common.truth.Truth.assertThat
import com.rmsr.myguard.domain.entity.QueryType
import com.rmsr.myguard.domain.entity.SearchQuery
import com.rmsr.myguard.domain.entity.isValidEGPhoneNumber
import org.junit.Assert.assertArrayEquals
import org.junit.Test
import kotlin.random.Random

class SearchQueryTest {

    @Test
    fun `right emails format isValidEMail Return true`() {

        val result = validEmailsList.map { SearchQuery.Email(it).isValid }

        assertThat(result).doesNotContain(false)
    }

    @Test
    fun `wrong emails format isValidEMail Return false`() {

        val result = inValidEmailsList.map { SearchQuery.Email(it).isValid }

        assertThat(result).doesNotContain(true)
    }

    @Test
    fun `right websites domains format isValidDomain Return true`() {

        val result = validDomainsList.map { SearchQuery.Domain(it).isValid }.toBooleanArray()
        val expected = List(result.size) { true }.toBooleanArray()

        assertArrayEquals(expected, result)
//        assertThat(result).containsExactlyElementsIn(expected)
    }

    @Test
    fun `wrong websites domains format isValidDomain Return false`() {
        val domains = listOf("  sdda", "sd", "", " ", ".....", "123584")
        val result = domains.map { SearchQuery.Domain(it).isValid }.toBooleanArray()
        val expected = List(result.size) { false }.toBooleanArray()

        assertArrayEquals(expected, result)
//        assertThat(result).containsExactlyElementsIn(expected)
    }

    @Test
    fun `right international phone numbers format isValidPhoneNumber Return true`() {
        val start = listOf("2010", "2011", "2012", "2015")
        val numbers = List(50) {
            start.get(Random.nextInt(0, 3)) + Random.nextLong(10000000, 99999999)
        }

        val result = numbers.map { SearchQuery.Phone(it).isValid }

        assertThat(result).doesNotContain(false)
    }

    @Test
    fun `wrong international phone numbers format isValidPhoneNumber Return false`() {
        val start = listOf("29010", "82011", "0212", "015", "512", "2000")
        val numbers = List(50) {
            start.get(Random.nextInt(0, 5)) + Random.nextLong(10000000, 99999999)
        }

        val result = numbers.map { SearchQuery.Phone(it).isValid }

        assertThat(result).doesNotContain(true)
    }

    @Test
    fun `right EG phone numbers format isValidEGPhoneNumber Return true`() {
        val start = listOf("010", "011", "012", "015")
        val numbers = List(50) {
            start.get(Random.nextInt(0, 3)) + Random.nextLong(10000000, 99999999)
        }

        val result = numbers.map { SearchQuery.Phone(it).isValidEGPhoneNumber }

        assertThat(result).doesNotContain(false)
    }

    @Test
    fun `assert first destructive component return query`() {
        val searchQuery = SearchQuery.Email("test query", "test hint")
        val (query) = searchQuery

        assertThat(query).isInstanceOf(String::class.java)
        assertThat(query).isEqualTo(searchQuery.query)
    }

    @Test
    fun `assert second destructive component return QueryType`() {
        val searchQuery = SearchQuery.Email("test query", "test hint")
        val (_, queryType) = searchQuery

        assertThat(queryType).isInstanceOf(QueryType::class.java)
        assertThat(queryType).isEqualTo(QueryType.EMAIL)
    }

    @Test
    fun `assert third destructive component return hint`() {
        val searchQuery = SearchQuery.Email("test query", "test hint")
        val (_, _, hint) = searchQuery

        assertThat(hint).isInstanceOf(String::class.java)
        assertThat(hint).isEqualTo(searchQuery.hint)
    }


    companion object {
        private val validEmailsList = listOf(
            "email@example.com",
            "firstname.lastname@example.com",
            "email@subdomain.example.com",
            "firstname+lastname@example.com",
            "email@123.123.123.123.co",
            "moh_.-amed@yaho-oo-mab.com",
            "1234567890@example.com",
            "email@example-one.com",
            "email@-example.com",
            "email@example.web",
            "_______@example.com",
            "email@example.name",
            "email@example.museum",
            "email@example.co.jp",
            "firstname-lastname@example.com"
        )
        private val inValidEmailsList = listOf(
            "", "  ", "plainaddress",
            "#@%^%#\$@#\$@#.com",
            "@example.com",
            "Joe Smith <email@example.com>",
            "email.example.com",
            "email@example@example.com",
            ".email@example.com",
            "email.@example.com",
            "email..email@example.com",
            "あいうえお@example.com",
            "email@[123.123.123.123].co",
            "\"email\"@example.com",
            "email@example.com (Joe Smith)",
            "email@example",
            "email@111.222.333.44444",
            "email@example..com",
            "Abc..123@example.com"
        )
        private val validDomainsList = listOf(
            "        cvxcv.com",
            "000webhost.com",
            "123rf.com",
            "126.com",
            "163.com",
            "17173.com",
            "17app.co",
            "2fast4u.be",
            "500px.com",
            "7k7k.com",
            "8fit.com",
            "8tracks.com",
            "abandonia.com",
            "abusewith.us",
            "acne.org",
            "adapt.io",
            "adobe.com",
            "adult-fanfiction.org",
            "adultfriendfinder.com",
            "adultfriendfinder.com",
            "aerserv.com",
            "agusiq-torrents.pl",
            "ahashare.com",
            "aipai.com",
            "aitype.com",
            "akparti.org.tr",
            "ancestry.com",
            "androidforums.com",
            "animaljam.com",
            "animegame.me",
            "anime-planet.com",
            "animoto.com",
            "apollo.io",
            "appartoo.com",
            "appen.com",
            "aptoide.com",
            "armorgames.com",
            "armyforceonline.com",
            "artsy.net",
            "artvalue.com",
            "ashleymadison.com",
            "astoriacompany.com",
            "astropid.com",
            "aternos.org",
            "atlasquantum.com",
            "audiusa.com",
            "autocentrum.pl",
            "avast.com",
            "babynames.com",
            "badoo.com",
            "bannerbit.com",
            "battlefieldheroes.com",
            "beautifulpeople.com",
            "bell.ca",
            "bell.ca",
            "bestialitysextaboo.com",
            "bigbasket.com",
            "bigmoneyjobs.com",
            "binweevils.com",
            "biohack.me",
            "bitcointalk.org",
            "bitly.com",
            "bittorrent.com",
            "blackhatworld.com",
            "blackspigot.com",
            "blankmediagames.com",
            "bluesnap.com",
            "bolt.cd",
            "bombuj.eu",
            "bonobos.com",
            "bookmate.com",
            "botoflegends.com",
            "brazzers.com",
            "btc-e.com",
            "btobet.com",
            "bukalapak.com",
            "businessacumen.biz",
            "cafemom.com",
            "cafepress.com",
            "cannabis.com",
            "canva.com",
            "cardmafia.cc",
            "cashcrate.com",
            "catho.com.br",
            "cdprojektred.com",
            "cfire.mail.ru",
            "chatbooks.com",
            "cheapassgamer.com",
            "chegg.com",
            "chowbus.com",
            "cit0day.in",
            "citybee.lt",
            "clearvoicesurveys.com",
            "clixsense.com",
            "cloudpets.com",
            "co188.com",
            "coachella.com",
            "coinmama.com",
            "comcast.net",
            "comelec.gov.ph",
            "covve.com",
            "cprewritten.net",
            "cprewritten.net",
            "crackcommunity.com",
            "cracked.to",
            "crackingforum.com",
            "creative.com",
            "d3scene.com",
            "dafont.com",
            "dailymotion.com",
            "dailyobjects.com",
            "dailyquiz.me",
            "dangdang.com",
            "daniweb.com",
            "data4marketers.com",
            "data4marketers.com",
            "datacamp.com",
            "datanleads.com",
            "dave.com",
            "ddo.com",
            "demonforums.net",
            "descomplica.com.br",
            "devkitpro.org",
            "diet.com",
            "digimon.co.in",
            "disqus.com",
            "dlh.net",
            "dodonew.com",
            "dominos.co.in",
            "drivesure.com",
            "drizly.com",
            "dropbox.com",
            "dubsmash.com",
            "duelingnetwork.com",
            "dunzo.com",
            "duowan.com",
            "dvd-shop.ch",
            "eatstreet.com",
            "edmodo.com",
            "elance.com",
            "elanic.in",
            "emuparadise.me",
            "epicbot.com",
            "epicgames.com",
            "epicnpc.com",
            "eroticy.com",
            "eservices.durban.gov.za",
            "ethereum.org",
            "europa.jobs",
            "evermotion.org",
            "everybodyedits.com",
            "evite.com",
            "evony.com",
            "exactis.com",
            "experian.com",
            "eyeem.com",
            "f.elex.com",
            "facebook.com",
            "facepunch.com",
            "faceup.dk",
            "factual.com",
            "fashionfantasygame.com",
            "fashionnexus.co.uk",
            "ffshrine.org",
            "fhostingesps6bly.onion",
            "filmai.in",
            "flashback.se",
            "flashflashrevolution.com",
            "flashflashrevolution.com",
            "fling.com",
            "flvs.net",
            "foodora.com",
            "forbes.com",
            "forum.btcsec.com",
            "forum.btcsec.com",
            "forumcommunity.net",
            "forums.boxee.com",
            "fotolog.com",
            "foxybingo.com",
            "freshmenu.com",
            "fridae.asia",
            "funimation.com",
            "funny-games.biz",
            "furaffinity.net",
            "gaadi.com",
            "gab.com",
            "gamerzplanet.net",
            "gamesalad.com",
            "game-tuts.com",
            "gamigo.com",
            "gatehub.net",
            "gawker.com",
            "ge.tt",
            "geekedin.net",
            "geniusu.com",
            "gfan.com",
            "ggumim.co.kr",
            "glofox.com",
            "gogames.me",
            "goldsilver.com",
            "gonitro.com",
            "gpotato.com",
            "gpsunderground.com",
            "gtagaming.com",
            "guntrader.uk",
            "hackforums.net",
            "hackingteam.com",
            "hautelook.com",
            "havenly.com",
            "healthnow.co",
            "hemmakvall.se",
            "hemmelig.com",
            "heroesofgaia.com",
            "heroesofnewerth.com",
            "hiapk.com",
            "hltv.org",
            "homechef.com",
            "hongfire.com",
            "hookers.nl",
            "hounddawgs.org",
            "houzz.com",
            "htcmania.com",
            "hthstudios.com",
            "hub4tech.com",
            "hurb.com",
            "i-dressup.com",
            "iimjobs.com",
            "ilikecheats.net",
            "imesh.com",
            "imgur.com",
            "indianrails.in",
            "insanelyi.com",
            "intelimost.com",
            "interpals.net",
            "intgovforum.org",
            "ipmart-forum.com",
            "ixigo.com",
            "jamesdelivery.com.br",
            "jd.com",
            "jefit.com",
            "jobandtalent.com",
            "jobstreet.com",
            "joomlart.com",
            "justdate.com",
            "kickstarter.com",
            "kimsufi.com",
            "kiwifarms.net",
            "km.ru",
            "knowncircle.com",
            "knuddels.de",
            "kreditplus.com",
            "lanwar.com",
            "last.fm",
            "lbsg.net",
            "leagueoflegends.com",
            "ledger.com",
            "leet.cc",
            "lifebear.com",
            "lightshope.org",
            "liker.com",
            "linkedin.com",
            "linuxforums.org",
            "linuxmint.com",
            "littlemonsters.com",
            "liveauctioneers.com",
            "livejournal.com",
            "livpure.com",
            "lizardstresser.su",
            "lookbook.nu",
            "lotro.com",
            "loungeboard.net",
            "luminpdf.com",
            "lyricsmania.com",
            "mac-forums.com",
            "mac-torrents.com",
            "mail.ru",
            "majorgeeks.com",
            "mall.cz",
            "malwarebytes.org",
            "mangadex.org",
            "mangafox.me",
            "mangatraders.com",
            "mappery.com",
            "mashable.com",
            "mate1.com",
            "mathway.com",
            "mcbans.com",
            "mdpi.com",
            "meetmindful.com",
            "mgmresorts.com",
            "mindjolt.com",
            "minecraftpeforum.net",
            "minecraftworldmap.com",
            "minefield.fr",
            "minehut.com",
            "minted.com",
            "mmgfusion.com",
            "mobifriends.com",
            "modaco.com",
            "modbsolutions.com",
            "moneybookers.com",
            "moneycontrol.com",
            "morele.net",
            "mortalonline.com",
            "mpgh.net",
            "mrexcel.com",
            "mspy.com",
            "muslimdirectory.co.uk",
            "muslimmatch.com",
            "myfha.net",
            "myfitnesspal.com",
            "myheritage.com",
            "myrepospace.com",
            "myspace.com",
            "myvidster.com",
            "nap.bg",
            "napsgear.org",
            "naughtyamerica.com",
            "nemoweb.net",
            "neopets.com",
            "neteller.com",
            "netgalley.com",
            "netlog.com",
            "netprospex.com",
            "netshoes.com.br",
            "nextgenupdate.com",
            "nexusmods.com",
            "nihonomaru.net",
            "nival.com",
            "nonnudegirls.org",
            "nulled.ch",
            "nulled.cr",
            "nurserycam.co.uk",
            "ogusers.com",
            "ogusers.com",
            "onverse.com",
            "opencsgo.com",
            "ordersnapp.com",
            "ordineavvocatiroma.it",
            "ovh.com",
            "OwnedCore.com",
            "oxfam.org.au",
            "paddypower.com",
            "parapa.mail.ru",
            "parkmobile.io",
            "patreon.com",
            "payasugym.com",
            "peatix.com",
            "pemiblanc.com",
            "peoplesenergy.co.uk",
            "petflow.com",
            "phonehouse.es",
            "phpfreaks.com",
            "pixelfederation.com",
            "pixlr.com",
            "pizap.com",
            "pizza.dominos.be",
            "planetcalypsoforum.com",
            "play-gar.com",
            "plex.tv",
            "pluto.tv",
            "pokebip.com",
            "pokemoncreed.net",
            "pokemonnegro.com",
            "policeone.com",
            "poshmark.com",
            "powerbot.org",
            "proctoru.com",
            "programmingforums.org",
            "promo.com",
            "promofarma.com",
            "proptiger.com",
            "ps3hax.net",
            "pspiso.com",
            "psx-scene.com",
            "qip.ru",
            "qnb.com",
            "quantumbooter.net",
            "quidd.co",
            "quinstreet.com",
            "r2games.com",
            "r2games.com",
            "rambler.ru",
            "rankwatch.com",
            "raychat.ir",
            "rbx.rocks",
            "realestatemogul.com",
            "redmart.lazada.sg",
            "reincubate.com",
            "retinax.com",
            "reverbnation.com",
            "rivercitymediaonline.com",
            "roll20.net",
            "romwe.com",
            "rosebuttboard.com",
            "russianamerica.com",
            "scentbird.com",
            "seedpeer.eu",
            "sephora.com.au",
            "serverpact.com",
            "sharethis.com",
            "shein.com",
            "shopback.com",
            "short-edition.com",
            "shotbow.net",
            "siae.it",
            "sktorrent.eu",
            "slickwraps.com",
            "smogon.com",
            "snail.com",
            "snapchat.com",
            "socialengineered.net",
            "solomid.net",
            "sonicbids.com",
            "sony.com",
            "soundwave.com",
            "specials.mastercard.de",
            "spirol.com",
            "sprashivai.ru",
            "spyfone.com",
            "staminus.net",
            "starnet.md",
            "startribune.com",
            "sterkinekor.co.za",
            "stockx.com",
            "storybird.com",
            "straffic.io",
            "stratfor.com",
            "streeteasy.com",
            "strongholdkingdoms.com",
            "sumotorrent.sx",
            "svenskamagic.com",
            "sweclockers.com",
            "swvl.com",
            "tailieu.vn",
            "tamodo.com",
            "taobao.com",
            "taringa.net",
            "technicpack.net",
            "teespring.com",
            "teracod.org",
            "tesco.com",
            "tgbus.com",
            "thecandidboard.com",
            "thefappening.so",
            "theflyonthewall.com",
            "thehalloweenspot.com",
            "thetvdb.com",
            "thewarinc.com",
            "thishabboforum.com",
            "tianya.cn",
            "ticketcounter.nl",
            "ticketfly.com",
            "tokopedia.com",
            "toondoo.com",
            "torrent-invites.com",
            "tout.com",
            "trai.gov.in",
            "travelok.com",
            "trillian.im",
            "truckersmp.com",
            "truefire.com",
            "tumblr.com",
            "uiggy.com",
            "ulmon.com",
            "underworldempireforums.com",
            "unicocampania.it",
            "universarium.org",
            "universityofcalifornia.edu",
            "unrealengine.com",
            "utahgunexchange.com",
            "utorrent.com",
            "uuu9.com",
            "vakinha.com.br",
            "vastaamo.fi",
            "vbulletin.com",
            "vedantu.com",
            "verifications.io",
            "verified.cm",
            "vianet.com.np",
            "victoryphones.com",
            "viewfines.co.za",
            "vk.com",
            "vodafone.is",
            "void.to",
            "vtechda.com",
            "vtightgel.com",
            "wanelo.com",
            "warframe.com",
            "warmane.com",
            "wattpad.com",
            "wedmegood.com",
            "weheartit.com",
            "weleakinfo.com",
            "whitepages.com",
            "whmcs.com",
            "wifelovers.com",
            "wiiuiso.com",
            "wildstar-online.com",
            "win7vista.com",
            "wishbone.io",
            "wishbone.io",
            "wizishop.fr",
            "wongnai.com",
            "wpsandbox.io",
            "wptapl.com",
            "xat.com",
            "xbox360iso.com",
            "xboxscene.com",
            "xhamster.com",
            "xiaomi.cn",
            "xkcd.com",
            "xpgamesaves.com",
            "xsplit.com",
            "yahoo.com",
            "yam.com",
            "yatra.com",
            "yotepresto.com",
            "youku.com",
            "younow.com",
            "youporn.com",
            "zhenai.com",
            "zing.vn",
            "zomato.com",
            "zoomcar.com",
            "zoosk.com",
            "zoosk.com",
            "zooville.org",
            "zynga.com",
        )
    }
}